### ISSUE TITLE
Panic when running example

### ISSUE THREAD

**Issue by HugoPeters1024** [dust-engine/NRD#2]
`cargo run --example example` yields the following panic:

```
    descriptor_pool_desc: DescriptorPoolDesc {
        sets_max_num: 75,
        constant_buffers_max_num: 60,
        samplers_max_num: 300,
        textures_max_num: 514,
        storage_textures_max_num: 189,
    },
}
[
    DispatchDesc {
        name: "Clear (f)",
        resources: [
            ResourceDesc {
                state_needed: StorageTexture,
                ty: TRANSIENT_POOL,
                index_in_pool: 5,
                mip_offset: 0,
                mip_num: 1,
            },
        ],
thread 'main' panicked at library/core/src/panicking.rs:215:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
[1]    98977 IOT instruction (core dumped)  cargo run --example example
```

### version info

```
rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)
```

**Comment by HugoPeters1024** [comment]
Here is the entire backtrace:

```
thread 'main' panicked at library/core/src/panicking.rs:215:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/panicking.rs:215:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/ub_checks.rs:66:21
   5: core::slice::raw::from_raw_parts
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/slice/raw.rs:96:9
   6: nrd_sys::ffi::DispatchDesc::constant_buffer
             at ./src/ffi.rs:778:13
   7: <nrd_sys::ffi::DispatchDesc as core::fmt::Debug>::fmt
             at ./src/ffi.rs:799:38
   8: <&T as core::fmt::Debug>::fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/mod.rs:2337:62
   9: core::fmt::builders::DebugSet::entry::{{closure}}
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/builders.rs:505:35
  10: core::fmt::builders::DebugInner::entry_with::{{closure}}
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/builders.rs:424:17
  11: core::result::Result<T,E>::and_then
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/result.rs:1321:22
  12: core::fmt::builders::DebugInner::entry_with
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/builders.rs:416:35
  13: core::fmt::builders::DebugSet::entry
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/builders.rs:505:9
  14: core::fmt::builders::DebugList::entries
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/builders.rs:695:13
  15: <[T] as core::fmt::Debug>::fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/mod.rs:2565:9
  16: <&T as core::fmt::Debug>::fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/mod.rs:2337:62
  17: core::fmt::rt::Argument::fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/rt.rs:142:9
  18: core::fmt::run
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/mod.rs:1201:5
  19: core::fmt::write
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/fmt/mod.rs:1169:26
  20: std::io::Write::write_fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/io/mod.rs:1843:15
  21: <&std::io::stdio::Stdout as std::io::Write>::write_fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/io/stdio.rs:776:9
  22: <std::io::stdio::Stdout as std::io::Write>::write_fmt
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/io/stdio.rs:750:9
  23: std::io::stdio::print_to
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/io/stdio.rs:1087:21
  24: std::io::stdio::_print
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/std/src/io/stdio.rs:1164:5
  25: example::main
             at ./examples/example.rs:24:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/9d79cd5f79e75bd0d2083260271307ce9acd9081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
[1]    103271 IOT instruction (core dumped)  RUST_BACKTRACE=1 cargo run --example example
```
